[project]
name = "playlist-evaluator"
version ="0.1.0"
description = "Evaluate LLM-generated playlists based on prompt alignment, cohesion, and cleverness"
authors = [{name = "brndnknn"}]
dependencies = []

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"